### ISSUE TITLE
EPI2ME Labs Pangolin does not appear to Update Pangolin when checking "Update Data"

### ISSUE THREAD

**Issue by mgurbano** [epi2me-labs/wf-artic#112]
### Ask away!

Good Morning All,
First off I am a huge fan of wf-artic and this pre-packaged analysis software.
I have always selected the check box within EPI2ME labs to "update data" [which says it updates Pangolin and Nextclade data at runtime] every time I run analysis. I was wondering why it never updated my Pangolin from version 4.1.3 to version 4.3 as I assumed it would have been. Am I understanding something incorrectly here? I have recently updated the wf-artic workflow and now I am on Pangolin version 4.3 as a result of that update, but I had thought I was constantly up to date because of this check box. Any info would be appreciated!
Best,
Matt

**Comment by mgurbano** [comment]
Update: when I look at an analyzed run, it says that I was running Pangolin Version 4.3.1 and Pangolin Data Version 1.29, which are the most up to date versions. Does this mean that it was actually updating and running the correct versions, but my Invocation logs were still saying I was using V4.1.3 because I hadn't updated the wf-artic workflow?

**Comment by bede** [comment]
Hi Matt,
Apologies for delay. Have you resolved the issue? If you can see `pangolin-data` version `1.29` in the HTML report's version table, you can be sure that Pangolin was updated at runtime, since the current container bundles an older version than this.

Versions of wf-artic prior to `v0.3.31` released in August 2023 did not update Pangolin and Nextclade by default, so if you were using an old version of wf-artic you may not have generated up to date lineage calls (unless manually setting `--update_data` to true).

Thanks,
Bede

**Comment by mgurbano** [comment]
Good Afternoon Bede,

Upon reexamination, that is not the resolution that I included on Aug 15. I thought this was a different ONT github forum post on a quick scan. That is my fault. This situation has been resolved, though. It turned out that it was actually pulling the correct and most updated version, but in the software it looked like it wasn't! This has since been fixed with a newer version of EPI2ME Labs, I'm sorry that I can't remember which version update did it.

Best,
Matt Urbano


* * * * * * *
Matthew Urbano
Genomics Lead Scientist, Virginia Tech Molecular Diagnostics Laboratory
Fralin Biomedical Research Institute at VTC
* * * * * * *
________________________________

**Comment by bede** [comment]
Hi Matt,
I'm glad to hear you've resolved this – thanks for following up. 

Best,
Bede
