### ISSUE TITLE
docker image can't be built Dockerfile

### ISSUE THREAD

**Issue by DABAKER165** [epi2me-labs/wf-artic#12]
I am getting the following error when building the docker.   I split up the RUN statement to focus on the error region:
Step 6/8 : RUN . $CONDA_DIR/etc/profile.d/mamba.sh     && micromamba activate     && micromamba clean --all --yes
 ---> Running in 2e684fa6976a
The following arguments were not expected: --yes --all clean
Run with --help for more information.

 It looks like the micromamba Version: 0.7.13 gets installed automatically and is missing the clean subcommand:
Subcommands:
  shell                       Generate shell init scripts
  create                      Create new environment
  install                     Install packages in active environment
  remove                      Remove packages from active environment
  list                        List packages in active environment
  constructor                 Commands to support using micromamba in constructor

It looks like version 0.13.1 and later gets the clean command (April 23 2021 commit) though the versioning is less than clear with micromamba.

**Comment by cjw85** [comment]
Hi @DABAKER165,

The docker images are available on dockerhub, there should be no reason to build them yourself. In fact there should be no reason to use this repository directly for any reason, it exists only so that nextflow can gain access to it.

If you are intent on building the images, I believe the issue is that this line:

    ARG BASEIMAGE=ontresearch/base-workflow-image:v0.1.0

is incorrect and should be changed to use the latest tagged version of that image on dockerhub.
