### ISSUE TITLE
Analysis Failed but Coverage is Working

### ISSUE THREAD

**Issue by Ceres90** [epi2me-labs/wf-artic#21]
After running the nextflow workflow and it appearing to successfully run. The sequencing report seems to show some issues. 

The reads were successfully mapped by the analysis failed which seems to indicate most of the tools did not actually work. 

I am using  N E X T F L O W  ~  version 21.10.0  with the latest release wf-artic (v0.3.5)  and one of your test files. 

Any thoughts as to what the issue might be? 

![Screenshot 2021-11-30 123547](https://user-images.githubusercontent.com/95306501/144098658-6ba24536-b528-4b4f-8f6d-80420c4d87dc.png)

**Comment by mattdmem** [comment]
Hello,

Could you please post the command you used to run the workflow?

Thanks!

**Comment by Ceres90** [comment]
nextflow run epi2me-labs/wf-artic -profile conda --fastq /home/ceres/fastqfiles/ --out_dir "Output_5PA"

**Comment by mattdmem** [comment]
Thanks... Could you try running with the included test_data please? If you clone this repo you'll find it in the `test_data` folder. Then `--fastq` should be `<path_to_repo>/wf-artic/test_data/sars-samples-demultiplexed`

**Comment by Ceres90** [comment]
I can try it again but the fastq file I used was one of the test_data files (the file in barcode 2) , does the program need multiple files to work properly or is there something else in that folder that allows it to work?

**Comment by mattdmem** [comment]
Did you have any errors that you could share? What did the output of nextflow look like?

**Comment by bede** [comment]
This is one of the issues I encountered running wf-artic on a cluster where the compute nodes lack connectivity. For me it was Medaka failing silently because it could not download the model the first time it was run. After it has downloaded once, it runs fine without connectivity. Your error may of course be caused by something different. Look inside the work directory for clues as to what is going wrong with runArtic.

@mattdmem Perhaps runArtic should crash when model download fails, although this is probably a Medaka thing?

**Comment by Ceres90** [comment]
how did you get it to download ?

**Comment by Ceres90** [comment]
its fixed now, i reinstalled everything this time I had to enable virtual machine usage in my bios than just followed the below how to 
https://labs.epi2me.io/nextflow-on-windows/

I
