### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by Ceres90** [epi2me-labs/wf-artic#30]
What is the naming convention of the barcode folders allowed to be, I would like to name them something besides just barcode01 but it seems to cause an issue when i do?

**Comment by mattdmem** [comment]
Thanks @Ceres90, the tool is designed to be run on the output of MinKNOW/guppy, which places reads into barcode folders in the format barcodeXX. Because this workflow is tied to this output style there is no plan at the moment to support barcode directories called anything else.

You can always call the directories what you like and use soft links to recreate the structure that the workflow expects?
