### ISSUE TITLE
error with samples

### ISSUE THREAD

**Issue by Hedi65** [epi2me-labs/wf-artic#7]
hi

i am quite new in MinION feild and i wanted to just test the pipeline . no problem with installation. i already have one demultiplexed fastq file and i made the sample sheet my self exactly as   yours in the test data and my command line is bellow. for some reasons it says sample is missing. no log file is created though it says check the log file.

any helps appreciated. 

nextflow run epi2me-labs/wf-artic \-w home/Out -profile standard --fastq test.fastq --samples sample_sheet --out_dir
N E X T F L O W  ~  version 21.04.1
Launching `epi2me-labs/wf-artic` [jolly_montalcini] - revision: 55e68f6c47 [master]

Parameter summary
=================
    help: false
    out_dir: true
    fastq: test.fastq
    samples: sample_sheet
    report_depth: 100
    medaka_model: r941_min_high_g360
    scheme_name: SARS-CoV-2
    scheme_version: V3
    genotype_variants: null
    detect_samples: false
    report_clade: true
    report_lineage: true
    report_coverage: true
    report_variant_summary: true
    wfversion: v0.2.3
    aws_image_prefix: null
    aws_queue: null
    lab_id: null
    testkit: null
    _min_len: 400
    _max_len: 700

No such variable: samples

 -- Check script '/home/.nextflow/assets/epi2me-labs/wf-artic/main.nf' at line: 503 or see '.nextflow.log' file for more details

**Comment by cjw85** [comment]
Hi @Hedi65,

I think the workflow is getting a little confused as your `--fastq` option is a file rather than a directory; from the help message the code expects (and assumes) the value to be a directory. Can you place your single `test.fastq` file within ` directory, so e.g. `reads/test.fastq` and then provide the option `--fastq reads` with everything else the same.

We'll take a look at making the code behave more sensibly here, as I imagine what you have done is a common mistake.

**Comment by Hedi65** [comment]
thank you for your suggestion. yes it does work. however we experienced some other errors  as displayed bellow. we got some results in output folder but we are wondering how we could resolve the new error. 

nextflow run epi2me-labs/wf-artic \-w WD -profile conda --fastq /home/Lin/Downloads/Hospital_One_Sample/Untitled  --samples sample_sheet --out_dir ./test
N E X T F L O W  ~  version 21.04.1
Launching `epi2me-labs/wf-artic` [maniac_goodall] - revision: 55e68f6c47 [master]

Parameter summary
=================
    help: false
    out_dir: ./test
    fastq: /home/Lin/Downloads/Hospital_One_Sample/Untitled
    samples: sample_sheet
    report_depth: 100
    medaka_model: r941_min_high_g360
    scheme_name: SARS-CoV-2
    scheme_version: V3
    genotype_variants: null
    detect_samples: false
    report_clade: true
    report_lineage: true
    report_coverage: true
    report_variant_summary: true
    wfversion: v0.2.3
    aws_image_prefix: null
    aws_queue: null
    lab_id: null
    testkit: null
    _min_len: 400
    _max_len: 700

[-        ] process > checkSampleSheet       -
executor >  local (11)
executor >  local (11)
executor >  local (11)
executor >  local (11)
executor >  local (13)
[97/99e58a] process > checkSampleSheet (1)    [100%] 1 of 1 ✔
[1e/3019d0] process > pipeline:copySchemeDir  [100%] 1 of 1 ✔
[32/5e6fef] process > pipeline:preArticQC (1) [100%] 1 of 1 ✔
[a8/3f30cd] process > pipeline:runArtic (1)   [100%] 1 of 1 ✔
[63/58d95c] process > pipeline:allConsensus   [100%] 1 of 1 ✔
[69/b0d4ca] process > pipeline:allVariants    [100%] 1 of 1 ✔
[53/8eb800] process > pipeline:nextclade      [100%] 1 of 1 ✔
[27/cecfc2] process > pipeline:pangolin       [100%] 1 of 1 ✔
[f1/5facc7] process > pipeline:report         [  0%] 0 of 1
[9c/095036] process > output (1)              [100%] 4 of 4
Error executing process > 'pipeline:report'

Caused by:
  Process `pipeline:report` terminated with an error exit status (1)

Command executed:

  echo "--pangolin pangolin.csv"
      echo "--nextclade nextclade.json"
      echo "help,false
  out_dir,./test
  fastq,/home/Lin/Downloads/Hospital_One_Sample/Untitled
  samples,sample_sheet
  report_depth,100
  medaka_model,r941_min_high_g360
  scheme_name,SARS-CoV-2
  scheme_version,V3
  genotype_variants,null
  detect_samples,false
  report_clade,true
  report_lineage,true
  report_coverage,true
  report_variant_summary,true
  wfversion,v0.2.3
  aws_image_prefix,null
  aws_queue,null
  lab_id,null
  testkit,null
  _min_len,400
  _max_len,700
  full_scheme_name,SARS-CoV-2/V3" > params.csv
      report.py         consensus_status.txt wf-artic-report.html         --pangolin pangolin.csv --nextclade nextclade.json           --revision master --params params.csv --commit 55e68f6c47fd595ec06e249f646c7610e418e203         --min_len 400 --max_len 700 --report_depth         100 --depths depth_stats/* --summaries read_stats/*         --bcftools_stats vcf_stats/*

Command exit status:
  1

Command output:
  --pangolin pangolin.csv
  --nextclade nextclade.json

Command error:
  Traceback (most recent call last):
    File "/home/Lin/.nextflow/assets/epi2me-labs/wf-artic/bin/report.py", line 378, in <module>
      main()
    File "/home/Lin/.nextflow/assets/epi2me-labs/wf-artic/bin/report.py", line 359, in main
executor >  local (13)
[97/99e58a] process > checkSampleSheet (1)    [100%] 1 of 1 ✔
[1e/3019d0] process > pipeline:copySchemeDir  [100%] 1 of 1 ✔
[32/5e6fef] process > pipeline:preArticQC (1) [100%] 1 of 1 ✔
[a8/3f30cd] process > pipeline:runArtic (1)   [100%] 1 of 1 ✔
[63/58d95c] process > pipeline:allConsensus   [100%] 1 of 1 ✔
[69/b0d4ca] process > pipeline:allVariants    [100%] 1 of 1 ✔
[53/8eb800] process > pipeline:nextclade      [100%] 1 of 1 ✔
[27/cecfc2] process > pipeline:pangolin       [100%] 1 of 1 ✔
[f1/5facc7] process > pipeline:report         [100%] 1 of 1, failed: 1 ✘
[9c/095036] process > output (1)              [100%] 4 of 4 ✔
Error executing process > 'pipeline:report'

Caused by:
  Process `pipeline:report` terminated with an error exit status (1)

Command executed:

  echo "--pangolin pangolin.csv"
      echo "--nextclade nextclade.json"
      echo "help,false
  out_dir,./test
  fastq,/home/Lin/Downloads/Hospital_One_Sample/Untitled
  samples,sample_sheet
  report_depth,100
  medaka_model,r941_min_high_g360
  scheme_name,SARS-CoV-2
  scheme_version,V3
  genotype_variants,null
  detect_samples,false
  report_clade,true
  report_lineage,true
  report_coverage,true
  report_variant_summary,true
  wfversion,v0.2.3
  aws_image_prefix,null
  aws_queue,null
  lab_id,null
  testkit,null
  _min_len,400
  _max_len,700
  full_scheme_name,SARS-CoV-2/V3" > params.csv
      report.py         consensus_status.txt wf-artic-report.html         --pangolin pangolin.csv --nextclade nextclade.json           --revision master --params params.csv --commit 55e68f6c47fd595ec06e249f646c7610e418e203         --min_len 400 --max_len 700 --report_depth         100 --depths depth_stats/* --summaries read_stats/*         --bcftools_stats vcf_stats/*

Command exit status:
  1

Command output:
  --pangolin pangolin.csv
  --nextclade nextclade.json

Command error:
  Traceback (most recent call last):
    File "/home/Lin/.nextflow/assets/epi2me-labs/wf-artic/bin/report.py", line 378, in <module>
      main()
    File "/home/Lin/.nextflow/assets/epi2me-labs/wf-artic/bin/report.py", line 359, in main
      versions = conda_versions.scrape_data(
    File "/home/Lin/.nextflow/assets/epi2me-labs/wf-artic/bin/conda_versions.py", line 24, in scrape_data
      proc = subprocess.run(cmd, shell=True, check=True, capture_output=True)
    File "/home/Lin/Downloads/Hospital_One_Sample/WD/conda/epi2melabs-nf-artic-f2618507edb267557c06679dbd9c4b0a/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '
  . ~/conda/etc/profile.d/mamba.sh;
  micromamba activate;
  micromamba list;
      ' returned non-zero exit status 2.

Work dir:
  /home/Lin/Downloads/Hospital_One_Sample/WD/f1/5facc7df201457fd25761cd9e6a8dc

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by cjw85** [comment]
@geocarvalho 
Can you please start a new issue, detailing the command you are running at the contents of your sample sheet file.

**Comment by noutin2020** [comment]
ISSUE: -- Check script '.nextflow/assets/epi2me-labs/wf-artic/main.nf' at line: 445 or see '.nextflow.log' file for more details

I am analysing SARS-CoV-2 sequence data generatd using midnight protocol.
I suscessfully installed NEXFLOW as shown below:

$ nextflow run hello
N E X T F L O W  ~  version 22.10.6
Pulling nextflow-io/hello ...
 downloaded from https://github.com/nextflow-io/hello.git
Launching `https://github.com/nextflow-io/hello` [wise_kilby] DSL2 - revision: 4eab81bd42 [master]
executor >  local (4)
[eb/4cd1ec] process > sayHello (3) [100%] 4 of 4 ✔
Hola world!

Ciao world!

Bonjour world!

Hello world!

However, I got into trouble while trying to run the following pipeline:

~$ nextflow run epi2me-labs/wf-artic --scheme_name SARS-CoV-2 --scheme_version Midnight-ONT/V1 --min_len 200 --max_len 1100 --out_dir MidnightResults --fastq MidgnihtFastq -work-dir /tmp/
N E X T F L O W  ~  version 22.10.6
Launching `https://github.com/epi2me-labs/wf-artic` [hopeful_turing] DSL2 - revision: 0175e81492 [master]

||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-artic v0.3.21-g0175e81
--------------------------------------------------------------------------------
Core Nextflow options
  revision       : master
  runName        : hopeful_turing
  containerEngine: docker
  launchDir      : /home/seq-chuss
  workDir        : /tmp
  projectDir     : /home/seq-chuss/.nextflow/assets/epi2me-labs/wf-artic
  userName       : seq-chuss
  profile        : standard
  configFiles    : /home/seq-chuss/.nextflow/assets/epi2me-labs/wf-artic/nextflow.config

Input Options
  fastq          : MidgnihtFastq

Primer Scheme Selection
  scheme_version : Midnight-ONT/V1

Output Options
  out_dir        : MidnightResults

Advanced Options
  min_len        : 200
  max_len        : 1100

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-artic for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x


--------------------------------------------------------------------------------
This is epi2me-labs/wf-artic v0.3.21-g0175e81.
--------------------------------------------------------------------------------

      ------------------------------------
      Available Primer Schemes:
      ------------------------------------
      
  Name		Version
  SARS-CoV-2	Midnight-IDT/V1	
  SARS-CoV-2	ARTIC/V1	
  SARS-CoV-2	ARTIC/V2	
  SARS-CoV-2	ARTIC/V4	
  SARS-CoV-2	ARTIC/V4.1	
  SARS-CoV-2	ARTIC/V3	
  SARS-CoV-2	NEB-VarSkip/v1a-long	
  SARS-CoV-2	NEB-VarSkip/v2b	
  SARS-CoV-2	NEB-VarSkip/v1a	
  SARS-CoV-2	NEB-VarSkip/v2	
  SARS-CoV-2	Midnight-ONT/V1	
  SARS-CoV-2	Midnight-ONT/V2	
  SARS-CoV-2	Midnight-ONT/V3	
  spike-seq	ONT/V1	
  spike-seq	ONT/V4.1	

      ------------------------------------
      
Checking fastq input.
[-        ] process > pipeline:getVersions   -
[-        ] process > pipeline:getParams     -
[-        ] process > pipeline:copySchemeDir -
A process input channel evaluates to null

 **-- Check script '.nextflow/assets/epi2me-labs/wf-artic/main.nf' at line: 445 or see '.nextflow.log' file for more details**

The analysis startd very well and was interrupted several times. The nextflow package was installed using different approachs to solve the issue. But the issue keeps coming out. Kindly assist e to solve this.

The ubuntu verion is Ubuntu 18.04.6 LTS

**Comment by noutin2020** [comment]
> @geocarvalho Can you please start a new issue, detailing the command you are running at the contents of your sample sheet file.

There is some bugs with this pipeline, please.

Error executing process > 'pipeline:preArticQC (9)'

Below is my run:

~$ nextflow run epi2me-labs/wf-artic --scheme_name SARS-CoV-2 --scheme_version Midnight-ONT/V1 --min_len 200 --max_len 1100 --out_dir MidnightResults --fastq IH_midnight_Fastq/ -work-dir /tmp/
N E X T F L O W  ~  version 22.10.6
Launching `https://github.com/epi2me-labs/wf-artic` [happy_miescher] DSL2 - revision: 0175e81492 [master]

||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-artic v0.3.21-g0175e81
--------------------------------------------------------------------------------
Core Nextflow options
  revision       : master
  runName        : happy_miescher
  containerEngine: docker
  launchDir      : /home/seq-chuss
  workDir        : /tmp
  projectDir     : /home/seq-chuss/.nextflow/assets/epi2me-labs/wf-artic
  userName       : seq-chuss
  profile        : standard
  configFiles    : /home/seq-chuss/.nextflow/assets/epi2me-labs/wf-artic/nextflow.config

Input Options
  fastq          : IH_midnight_Fastq/

Primer Scheme Selection
  scheme_version : Midnight-ONT/V1

Output Options
  out_dir        : MidnightResults

Advanced Options
  min_len        : 200
  max_len        : 1100

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-artic for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x


--------------------------------------------------------------------------------
This is epi2me-labs/wf-artic v0.3.21-g0175e81.
--------------------------------------------------------------------------------

      ------------------------------------
      Available Primer Schemes:
      ------------------------------------
      
  Name		Version
  SARS-CoV-2	Midnight-IDT/V1	
  SARS-CoV-2	ARTIC/V1	
  SARS-CoV-2	ARTIC/V2	
  SARS-CoV-2	ARTIC/V4	
  SARS-CoV-2	ARTIC/V4.1	
  SARS-CoV-2	ARTIC/V3	
  SARS-CoV-2	NEB-VarSkip/v1a-long	
  SARS-CoV-2	NEB-VarSkip/v2b	
  SARS-CoV-2	NEB-VarSkip/v1a	
  SARS-CoV-2	NEB-VarSkip/v2	
  SARS-CoV-2	Midnight-ONT/V1	
  SARS-CoV-2	Midnight-ONT/V2	
  SARS-CoV-2	Midnight-ONT/V3	
  spike-seq	ONT/V1	
  spike-seq	ONT/V4.1	

      ------------------------------------
      
Checking fastq input.
Barcoded directories detected.
executor >  local (5)
executor >  local (5)
executor >  local (5)
[-        ] process > pipeline:getVersions    [  0%] 0 of 1
[26/344854] process > pipeline:getParams      [100%] 1 of 1, failed: 1 ✘
[-        ] process > pipeline:copySchemeDir  [  0%] 0 of 1
[1a/d4b536] process > pipeline:preArticQC (7) [  3%] 3 of 94, failed: 3
[-        ] process > pipeline:runArtic       -
[-        ] process > pipeline:combineDepth   -
[-        ] process > pipeline:allConsensus   -
[-        ] process > pipeline:allVariants    -
[-        ] process > pipeline:prep_nextclade [  0%] 0 of 1
[-        ] process > pipeline:nextclade      -
[-        ] process > pipeline:pangolin       -
[-        ] process > pipeline:telemetry      -
[-        ] process > pipeline:report         -
[-        ] process > output                  -
Error executing process > 'pipeline:preArticQC (9)'

Caused by:
  Process `pipeline:preArticQC (9)` terminated with an error exit status (126)

Command executed:

  fastcat -s barcode07 -r barcode07.stats -x barcode07 > /dev/null

Command exit status:
  126

Command output:
  (empty)

Command error:
  docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=nxf-UPVf5s7ESads2vtpOxQlU1H3: dial unix /var/run/docker.sock: connect: permission denied.
  See 'docker run --help'.

Work dir:
  /tmp/30/8b1f1ff76831bc1defbf1cab92c77a

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`


WARN: Killing running tasks (1)

Kindly advise!!

**Comment by Yacsaw81** [comment]
Hi
I was using Minknow version 23.07.8 and I have just changed to Minknow version 24.06.8 to run SARS-CoV-2 sequencing on a MinION MK1B. At the end I used this Script: nextflow run epi2me-labs/wf-artic --scheme_name SARS-CoV-2 --
scheme_version Midnight-ONT/V1 --min_len 200 --max_len 1100 --out_dir  for the bioinformatics analysis and I got these messages:
Checking fastq input.
[-        ] process > pipeline:getVersions   -
[-        ] process > pipeline:getParams     -
[-        ] process > pipeline:copySchemeDir -
[-        ] process > pipeline:getVersions   -
[-        ] process > pipeline:getParams     -
[-        ] process > pipeline:copySchemeDir -
 Please help me

**Comment by mattdmem** [comment]
@Yacsaw81 please open a new ticket and include all of the requested information.

Thanks!

**Comment by Yacsaw81** [comment]
Dear
I didn't understand you, can you please be clearer?

Best regardsM. SAWADOGO YacoubaBiologiste médicalService de bactériologie virologieCHU Sourô Sanou de Bobo Dioulasso.Tel: (00226)70121792/78332809
 

    Le dimanche 13 octobre 2024 à 12:18:26 UTC, Matthew Parker ***@***.***> a écrit :  
 
 


@Yacsaw81 please open a new ticket and include all of the requested information.

Thanks!

**Comment by Yacsaw81** [comment]
Dear
I have just sent you can you confirm that it is ok now.

Best regards
M. SAWADOGO YacoubaBiologiste médicalService de bactériologie virologieCHU Sourô Sanou de Bobo Dioulasso.Tel: (00226)70121792/78332809
 

    Le dimanche 13 octobre 2024 à 12:27:16 UTC, Matthew Parker ***@***.***> a écrit :  
 
 


@Yacsaw81 please make a new issue:

https://github.com/epi2me-labs/wf-artic/issues/new/choose

and then include more information than you have provided here - you have not provided enough information for me to help you!

Matt
