### ISSUE TITLE
[enhancement]: wf-artic for other viruses - skip nextclade and pangolin

### ISSUE THREAD

**Issue by sarahryter** [epi2me-labs/wf-artic#77]
### What happened?

Hi guys,
this is more a follow up from a previous post (https://github.com/epi2me-labs/wf-artic/issues/38)
I successfully added the custom scheme and reference for another virus, but now I'm stuck at the nextclade and pangolin part as it is looking for SARS-CoV-2.
Is there a easy way to skip these steps and still get a report or is it at the moment only working for SARS-CoV-2? Did you had time to look into the implementation of other viruses?

Thanks for your feedback!

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

NA

### Relevant log output

```shell
NA
```

**Comment by mattdmem** [comment]
Hello @sarahryter,

I'm glad you got it working for another virus - at the moment, yes you're right that it's only really designed for SARS-CoV-2 so the nextclade and pangolin steps will always run.

Because the workflow was initially designed to address the needs of our users during the pandemic other viruses weren't really considered and nextclade and pangolin are pretty entangled in the workflow. I'll take a look at making these steps default but with the option to turn them off.

Matt

**Comment by kneubehl** [comment]
Are there any updates on this or an eta? Is this a priority? I'd like to use this pipeline since the report is very valuable but otherwise I will look into other tools. Thanks.

**Comment by mattdmem** [comment]
Hi @kneubehl - no ETA but work is ongoing on something to replace this workflow with something more generic. I'm going to close this issue. Keep on eye on `wf-amplicon` as it's likely this will be the basis for a replacement.
