### ISSUE TITLE
Unable to pull from repository

### ISSUE THREAD

**Issue by llk578496** [epi2me-labs/wf-artic#94]
### Operating System

Ubuntu 22.04

### Workflow Version

v0.3.30

### Workflow Execution

Command line

### CLI command run

`nextflow pull epi2me-labs/wf-artic`

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

Hi, we just tried to update the `wf-artic` by using the above command but seems it fails. May we seek your help? Thank you.

### Relevant log output

```shell
(nextflow) gilman_siu2@gilmansiu2-Z490-VISION-D:/mnt/data6/COVID$ nextflow pull epi2me-labs/wf-artic
Checking epi2me-labs/wf-artic ...
epi2me-labs/wf-artic contains uncommitted changes -- cannot pull from repository
```

**Comment by mattdmem** [comment]
Hello @llk578496,

This sometimes happens if you have changes in the previously pulled version of the workflow.

This is usually located in:

`~/.nextflow/assests/epi2me-labs/wf-artic`

Try deleting this directory if it exists and try `nextflow pull` again. Let me know if this works.

You could also try pulling the specific versions which you would like by specifying -r` - further details here: https://www.nextflow.io/docs/latest/cli.html#pull

Thanks

Matt

**Comment by llk578496** [comment]
It works. Thanks a lot.
